### ISSUE TITLE
memory leak of pending commmands responses

### ISSUE THREAD

**Issue by patricklx** [dfreeman/stagehand#8]
pendingCommands is never removed, causing all responses to be retained.

https://github.com/dfreeman/stagehand/blob/master/src/command-coordinator.ts#L33

**Comment by dfreeman** [comment]
Thank you for flagging this, @patricklx! I can't believe this leak has been hanging out for this long 😅 

At some point we might look at switching to [`comlink`](https://github.com/GoogleChromeLabs/comlink) in `ember-cli-typescript` instead, if we don't retire `ember-cli-typescript` entirely before that happens. In the meantime, though, I'll get a fix out!
